export const  REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const  REGISTRO_ERROR = "REGISTRO_ERROR";
export const  OBTENER_USUARIO = "OBTENER_USUARIO";
export const  LOGIN_EXITOSOS = "LOGIN_EXITOSOS";
export const  LOGIN_ERROR = "LOGIN_ERROR";
export const  CERRAR_SESION = "CERRAR_SESION";

export const  MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const  OCULTAR_ALERTA = "OCULTAR_ALERTA";

export const  OBTENER_CUSOS_INSTRUCTOR = "OBTENER_CUSOS_INSTRUCTOR";
export const  CURSOS_ERROR = "CURSOS_ERROR";
export const  CURSOS_AGREGAR = "AGREGAR_CURSOS";
export const  CURSOS_POR_ID = "CURSOS_POR_ID";
