export const  REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const  REGISTRO_ERROR = "REGISTRO_ERROR";
export const  OBTENER_USUARIO = "OBTENER_USUARIO";
export const  LOGIN_EXITOSOS = "LOGIN_EXITOSOS";
export const  LOGIN_ERROR = "LOGIN_ERROR";
export const  CERRAR_SESION = "CERRAR_SESION";

export const  MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const  OCULTAR_ALERTA = "OCULTAR_ALERTA";

export const  OBTENER_CUSOS_INSTRUCTOR = "OBTENER_CUSOS_INSTRUCTOR";
export const  CURSOS_ERROR = "CURSOS_ERROR";
export const  CURSOS_AGREGAR = "AGREGAR_CURSOS";
export const  CURSOS_EDITAR = "CURSOS_EDITAR";
export const  CURSOS_POR_ID = "CURSOS_POR_ID";
export const  CURSOS_FORM_TEMACURSO = "CURSOS_FORM_TEMACURSO";
export const  CURSOS_GUARDAR_TEMA_CURSO = "CURSOS_GUARDAR_TEMA_CURSO";
export const  CURSOS_AGREGAR_SUBTEMA_CURSO = "CURSOS_AGREGAR_SUBTEMA_CURSO";
export const  CURSOS_EDITAR_TEMA_CURSO = "CURSOS_EDITAR_TEMA_CURSO";
export const  CURSOS_ELIMINAR_TEMA_CURSO = "CURSOS_ELIMINAR_TEMA_CURSO";

export const  CURSOS_FORM_SUBTEMA = "CURSOS_FORM_SUBTEMA";
export const  CURSOS_SET_IDTEMA = "CURSOS_SET_IDTEMA";
export const  CURSOS_GUARDAR_SUBTEMA_CURSO = "CURSOS_GUARDAR_SUBTEMA_CURSO";
export const  CURSOS_EDITAR_SUBTEMA_CURSO = "CURSOS_EDITAR_SUBTEMA_CURSO";
export const  CURSOS_ELIMINAR_SUBTEMA_CURSO = "CURSOS_ELIMINAR_SUBTEMA_CURSO";
export const  CURSOS_OBTENER_SUBTEMAS_CURSO = "CURSOS_OBTENER_SUBTEMAS_CURSO";
export const  CURSOS_VACIAR_SUBTEMAS_CURSO = "CURSOS_VACIAR_SUBTEMAS_CURSO";



export const  CURSOS_EDICION_HERRAMIENTA = "CURSOS_EDICION_HERRAMIENTA";
export const  CURSOS_ELIMINAR_HERRAMIENTA = "CURSOS_ELIMINAR_HERRAMIENTA";
export const  CURSOS_EDICION_HERRAMIENTA_DOC = "CURSOS_EDICION_HERRAMIENTA_DOC";
export const  CURSOS_ELIMINAR_HERRAMIENTA_DOC = "CURSOS_ELIMINAR_HERRAMIENTA_DOC";
export const  CURSOS_AGREGAR_HERRAMIENTA_DOC = "CURSOS_AGREGAR_HERRAMIENTA_DOC";

//reproductor video
export const  CURSO_REPRODUCTOR_OBTENER_CONTENIDO = "CURSO_REPRODUCTOR_OBTENER_CONTENIDO";
export const  CURSO_REPRODUCTOR_OBTENER_CONTENIDO_EXITO = "CURSO_REPRODUCTOR_OBTENER_CONTENIDO_EXITO";
export const  CURSO_REPRODUCTOR_OBTENER_CONTENIDO_ERROR = "CURSO_REPRODUCTOR_OBTENER_CONTENIDO_ERROR";
export const  CURSO_REPRODUCTOR_SET__PRIMER_VIDEO = "CURSO_REPRODUCTOR_SET__PRIMER_VIDEO";
//DASHBOARD ALUMNO
export const  OBTENER_CURSOS_ALUMNO = "OBTENER_CURSOS_ALUMNO";
export const  OBTENER_CURSOS_ALUMNO_ERROR = "OBTENER_CURSOS_ALUMNO_ERROR";

// obtener curso para venta
export const  CURSO_VENTA_OBTENER_CONTENIDO = "CURSO_VENTA_OBTENER_CONTENIDO";
export const  CURSO_VENTA_OBTENER_CONTENIDO_EXITO = "CURSO_VENTA_OBTENER_CONTENIDO_EXITO";
export const  CURSO_VENTA_OBTENER_CONTENIDO_ERROR = "CURSO_VENTA_OBTENER_CONTENIDO_ERROR";

export const  LIMPIAR_STATE = "LIMPIAR_STATE";
export const  LIMPIAR_MENSAJE = "LIMPIAR_MENSAJE";
export const  LOADING_CURSO = "LOADING_CURSO";




