export const  REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const  REGISTRO_ERROR = "REGISTRO_ERROR";
export const  OBTENER_USUARIO = "OBTENER_USUARIO";
export const  LOGIN_EXITOSOS = "LOGIN_EXITOSOS";
export const  LOGIN_ERROR = "LOGIN_ERROR";
export const  CERRAR_SESION = "CERRAR_SESION";

export const  MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const  OCULTAR_ALERTA = "OCULTAR_ALERTA";

export const  OBTENER_CUSOS_INSTRUCTOR = "OBTENER_CUSOS_INSTRUCTOR";
export const  CURSOS_ERROR = "CURSOS_ERROR";
export const  CURSOS_AGREGAR = "AGREGAR_CURSOS";
export const  CURSOS_EDITAR = "CURSOS_EDITAR";
export const  CURSOS_POR_ID = "CURSOS_POR_ID";
export const  CURSOS_FORM_TEMACURSO = "CURSOS_FORM_TEMACURSO";
export const  CURSOS_GUARDAR_TEMA_CURSO = "CURSOS_GUARDAR_TEMA_CURSO";
export const  CURSOS_AGREGAR_SUBTEMA_CURSO = "CURSOS_AGREGAR_SUBTEMA_CURSO";
export const  CURSOS_EDITAR_TEMA_CURSO = "CURSOS_EDITAR_TEMA_CURSO";
export const  CURSOS_ELIMINAR_TEMA_CURSO = "CURSOS_ELIMINAR_TEMA_CURSO";

export const  CURSOS_FORM_SUBTEMA = "CURSOS_FORM_SUBTEMA";
export const  CURSOS_SET_IDTEMA = "CURSOS_SET_IDTEMA";
export const  CURSOS_GUARDAR_SUBTEMA_CURSO = "CURSOS_GUARDAR_SUBTEMA_CURSO";
export const  CURSOS_EDITAR_SUBTEMA_CURSO = "CURSOS_EDITAR_SUBTEMA_CURSO";
export const  CURSOS_ELIMINAR_SUBTEMA_CURSO = "CURSOS_ELIMINAR_SUBTEMA_CURSO";
export const  CURSOS_OBTENER_SUBTEMAS_CURSO = "CURSOS_OBTENER_SUBTEMAS_CURSO";
export const  CURSOS_VACIAR_SUBTEMAS_CURSO = "CURSOS_VACIAR_SUBTEMAS_CURSO";

export const  MAX_FILE_UPLOAD = "MAX_FILE_UPLOAD";
export const  MAX_FILE_UPLOAD_ERROR = "MAX_FILE_UPLOAD_ERROR";

export const  CURSOS_EDICION_HERRAMIENTA = "CURSOS_EDICION_HERRAMIENTA";
export const  CURSOS_ELIMINAR_HERRAMIENTA = "CURSOS_ELIMINAR_HERRAMIENTA";
export const  CURSOS_EDICION_HERRAMIENTA_DOC = "CURSOS_EDICION_HERRAMIENTA_DOC";
export const  CURSOS_ELIMINAR_HERRAMIENTA_DOC = "CURSOS_ELIMINAR_HERRAMIENTA_DOC";
export const  CURSOS_AGREGAR_HERRAMIENTA_DOC = "CURSOS_AGREGAR_HERRAMIENTA_DOC";

//reproductor video
export const  CURSO_REPRODUCTOR_OBTENER_CONTENIDO = "CURSO_REPRODUCTOR_OBTENER_CONTENIDO";
export const  CURSO_REPRODUCTOR_OBTENER_CONTENIDO_EXITO = "CURSO_REPRODUCTOR_OBTENER_CONTENIDO_EXITO";
export const  CURSO_REPRODUCTOR_OBTENER_CONTENIDO_ERROR = "CURSO_REPRODUCTOR_OBTENER_CONTENIDO_ERROR";
export const  CURSO_REPRODUCTOR_SET__PRIMER_VIDEO = "CURSO_REPRODUCTOR_SET__PRIMER_VIDEO";
//DASHBOARD ALUMNO
export const  OBTENER_CURSOS_ALUMNO = "OBTENER_CURSOS_ALUMNO";
export const  OBTENER_CURSOS_ALUMNO_ERROR = "OBTENER_CURSOS_ALUMNO_ERROR";

// obtener curso para venta
export const  CURSO_VENTA_OBTENER_CONTENIDO = "CURSO_VENTA_OBTENER_CONTENIDO";
export const  CURSO_VENTA_OBTENER_CONTENIDO_EXITO = "CURSO_VENTA_OBTENER_CONTENIDO_EXITO";
export const  CURSO_VENTA_OBTENER_CONTENIDO_ERROR = "CURSO_VENTA_OBTENER_CONTENIDO_ERROR";

export const  LIMPIAR_STATE = "LIMPIAR_STATE";
export const  LIMPIAR_MENSAJE = "LIMPIAR_MENSAJE";
export const  LOADING_CURSO = "LOADING_CURSO";

export const  OBTENER_DATOS_INSTRUCTOR_INICIO = "OBTENER_DATOS_INSTRUCTOR_INICIO";
export const  OBTENER_DATOS_INSTRUCTOR_EXITO = "OBTENER_DATOS_INSTRUCTOR_EXITO";
export const  OBTENER_DATOS_INSTRUCTOR_ERROR = "OBTENER_DATOS_INSTRUCTOR_ERROR";
//editar instructor
export const  EDITAR_DATOS_INSTRUCTOR_INICIO = "EDITAR_DATOS_INSTRUCTOR_INICIO";
export const  EDITAR_DATOS_INSTRUCTOR_EXITO = "EDITAR_DATOS_INSTRUCTOR_EXITO";
export const  EDITAR_DATOS_INSTRUCTOR_ERROR = "EDITAR_DATOS_INSTRUCTOR_ERROR";

export const  ALTA_DATOS_INSTRUCTOR_PROFESION_INICIO = "ALTA_DATOS_INSTRUCTOR_PROFESION_INICIO";
export const  ALTA_DATOS_INSTRUCTOR_PROFESION_EXITO = "ALTA_DATOS_INSTRUCTOR_PROFESION_EXITO";
export const  ALTA_DATOS_INSTRUCTOR_PROFESION_ERROR = "ALTA_DATOS_INSTRUCTOR_PROFESION_ERROR";

//CATEGORIAS
    export const OBTENER_DATOS_CATEGORIAS_INICIO = 'OBTENER_DATOS_CATEGORIAS_INICIO';
    export const OBTENER_DATOS_CATEGORIAS_EXITO = 'OBTENER_DATOS_CATEGORIAS_EXITO';
    export const OBTENER_DATOS_CATEGORIAS_ERROR = 'OBTENER_DATOS_CATEGORIAS_ERROR';

export const EDITAR_DATOS_CATEGORIAS_INICIO = 'EDITAR_DATOS_CATEGORIAS_INICIO';
export const EDITAR_DATOS_CATEGORIAS_EXITO = 'EDITAR_DATOS_CATEGORIAS_EXITO';
export const EDITAR_DATOS_CATEGORIAS_ERROR = 'EDITAR_DATOS_CATEGORIAS_ERROR';
    
export const ELIMINAR_DATOS_CATEGORIAS_INICIO = 'ELIMINAR_DATOS_CATEGORIAS_INICIO';
export const ELIMINAR_DATOS_CATEGORIAS_EXITO = 'ELIMINAR_DATOS_CATEGORIAS_EXITO';
export const ELIMINAR_DATOS_CATEGORIAS_ERROR = 'ELIMINAR_DATOS_CATEGORIAS_ERROR';

export const AGREGAR_DATOS_CATEGORIAS_INICIO = 'AGREGAR_DATOS_CATEGORIAS_INICIO';
export const AGREGAR_DATOS_CATEGORIAS_EXITO = 'AGREGAR_DATOS_CATEGORIAS_EXITO';
export const AGREGAR_DATOS_CATEGORIAS_ERROR = 'AGREGAR_DATOS_CATEGORIAS_ERROR';

export const OBTENER_DATOS_USUARIOS_ROL_INICIO ='OBTENER_DATOS_USUARIOS_ROL_INICIO';
export const OBTENER_DATOS_USUARIOS_ROL_EXITO ='OBTENER_DATOS_USUARIOS_ROL_EXITO';
export const OBTENER_DATOS_USUARIOS_ROL_ERROR ='OBTENER_DATOS_USUARIOS_ROL_ERROR';

export const  ELIMINAR_DATOS_USUARIOS_ROL_INICIO ='ELIMINAR_DATOS_USUARIOS_ROL_INICIO';
export const  ELIMINAR_DATOS_USUARIOS_ROL_EXITO ='ELIMINAR_DATOS_USUARIOS_ROL_EXITO';
export const  ELIMINAR_DATOS_USUARIOS_ROL_ERROR ='ELIMINAR_DATOS_USUARIOS_ROL_ERROR';

export const  ACTIVAR_DATOS_USUARIOS_ROL_INICIO = 'ACTIVAR_DATOS_USUARIOS_ROL_INICIO';
export const  ACTIVAR_DATOS_USUARIOS_ROL_EXITO = 'ACTIVAR_DATOS_USUARIOS_ROL_EXITO';
export const  ACTIVAR_DATOS_USUARIOS_ROL_ERROR = 'ACTIVAR_DATOS_USUARIOS_ROL_ERROR';

export const OBTENER_DATOS_CURSOS_USUARIOS_INICIO = 'OBTENER_DATOS_CURSOS_USUARIOS_INICIO';
export const OBTENER_DATOS_CURSOS_USUARIOS_EXITO = 'OBTENER_DATOS_CURSOS_USUARIOS_EXITO';
export const OBTENER_DATOS_CURSOS_USUARIOS_ERROR = 'OBTENER_DATOS_CURSOS_USUARIOS_ERROR';

export const  ACTIVAR_DATOS_USUARIOS_INSCRIPCION_INICIO = 'ACTIVAR_DATOS_USUARIOS_INSCRIPCION_INICIO';
export const  ACTIVAR_DATOS_USUARIOS_INSCRIPCION_EXITO = 'ACTIVAR_DATOS_USUARIOS_INSCRIPCION_EXITO';
export const  ACTIVAR_DATOS_USUARIOS_INSCRIPCION_ERROR = 'ACTIVAR_DATOS_USUARIOS_INSCRIPCION_ERROR';

export const  SUSPENDER_DATOS_USUARIOS_INSCRIPCION_EXITO = 'SUSPENDER_DATOS_USUARIOS_INSCRIPCION_EXITO';
export const  SUSPENDER_DATOS_USUARIOS_INSCRIPCION_ERROR = 'SUSPENDER_DATOS_USUARIOS_INSCRIPCION_ERROR';

export const  OBTENER_DATOS_CURSOS_USUARIO_NO_INSCRITO_INICIO= 'OBTENER_DATOS_CURSOS_USUARIO_NO_INSCRITO_INICIO';
export const  OBTENER_DATOS_CURSOS_USUARIO_NO_INSCRITO_EXITO= 'OBTENER_DATOS_CURSOS_USUARIO_NO_INSCRITO_EXITO';
export const  OBTENER_DATOS_CURSOS_USUARIO_NO_INSCRITO_ERROR= 'OBTENER_DATOS_CURSOS_USUARIO_NO_INSCRITO_ERROR';

export const  INSCRIBIR_USUARIO_CURSO_INICIO = 'INSCRIBIR_USUARIO_CURSO_INICIO';
export const  INSCRIBIR_USUARIO_CURSO_EXITO = 'INSCRIBIR_USUARIO_CURSO_EXITO';
export const  INSCRIBIR_USUARIO_CURSO_ERROR = 'INSCRIBIR_USUARIO_CURSO_ERROR';

export const DATOS_USUARIO_INICIO = 'DATOS_USUARIO_INICIO';
export const DATOS_USUARIO_EXITO = 'DATOS_USUARIO_EXITO';
export const DATOS_USUARIO_ERROR = 'DATOS_USUARIO_ERROR';